const crypto = require('crypto');
const { getClientAndDB } = require('./database.js')

// length: the amount of bytes to randomly generate
// prefix: if provided, this string will appear before the randomly generated bytes like this, ex. (`{prefix}27ca26fc-190d-44ca-846e-b3e6dd8640a6`)
function generateRandomBytes(length, prefix = null) {
    return new Promise((resolve, reject) => {
        crypto.randomBytes(12, (err, buff) => {
            if (err) {
                reject(err);
            }
            else {
                // if prefix is not null, preface the buffer with the prefix, if it is null, don't add a prefix
                const hexString = prefix !== null ? prefix + buff.toString('hex') : buff.toString('hex');
                resolve(hexString);
            }
        });
    });
}

async function generateUCID(dbConnection) {
    const bytes = await generateRandomBytes(12, "chat_");
    const collisionCheck = await dbConnection.collection('chats').findOne({ ucid: bytes });

    if (collisionCheck) {
        return await generateUCID(dbConnection);
    }
    return bytes;
}




module.exports = {
    generateUCID
};